project:
  type: website
  output-dir: docs
website:
  title: "Mel Balcarcel Arias"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

